### ISSUE TITLE
meson error

### ISSUE THREAD

**Issue by Faymoon** [open-source-parsers/jsoncpp#1076]
I get this error wen trying to compile with meson, i followed exactly the step from the building part of the wiki.
```
ninja: Entering directory `build-debug'
[1/4] /usr/bin/meson --internal symbolextractor libjsoncpp.so.22 'jsoncpp@sha/libjsoncpp.so.22.symbols'
FAILED: jsoncpp@sha/libjsoncpp.so.22.symbols
/usr/bin/meson --internal symbolextractor libjsoncpp.so.22 'jsoncpp@sha/libjsoncpp.so.22.symbols'
Traceback (most recent call last):
  File "/usr/bin/meson", line 11, in <module>
    load_entry_point('meson==0.52.0', 'console_scripts', 'meson')()
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 226, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 215, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 163, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/symbolextractor.py", line 118, in run
    gen_symbols(libfile, outfile, options.cross_host)
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/symbolextractor.py", line 105, in gen_symbols
    linux_syms(libfilename, outfilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/symbolextractor.py", line 63, in linux_syms
    raise RuntimeError('Readelf does not work')
RuntimeError: Readelf does not work
ninja: build stopped: subcommand failed.
```

**Comment by dota17** [comment]
> ninja: Entering directory `build-debug'

The **LIB_TYPE** only has three choice: `shared`, `static`, `both`, then it will produce three kind of directory: `build-shared`, `build-static`, `build-both`. So I don't know how you produced a build-debug directory. Maybe that's the problem.

**Comment by Faymoon** [comment]
It's a little error but the name of the directory is not a problem because i changed it on both commands, it doesn't really matter for the compiler.

**Comment by dota17** [comment]
Does your `readelf` command work properly? Which platform are you using? Which versions are the related rependencies in your platform?

**Comment by Faymoon** [comment]
the `readelf` command exists and seems to work. I am on debian:sid. And meson and python are up to date.

**Comment by Faymoon** [comment]
I tried the `meson wrap install jsoncpp` command and i get this error. `Subprojects dir not found. Run this script in your source root directory.` maybe it would be easier to fix

**Comment by Faymoon** [comment]
for the last error i just had to create a directory, i did it and now i get this :
```
Warning: SSL not available, traffic not authenticated.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/wrap/wraptool.py", line 216, in run
    options.wrap_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/wrap/wraptool.py", line 100, in install
    (branch, revision) = get_latest_version(name)
  File "/usr/lib/python3/dist-packages/mesonbuild/wrap/wraptool.py", line 83, in get_latest_version
    jd = get_result(API_ROOT + 'query/get_latest/' + name)
  File "/usr/lib/python3/dist-packages/mesonbuild/wrap/wraptool.py", line 57, in get_result
    u = open_wrapdburl(urlstring)
  File "/usr/lib/python3/dist-packages/mesonbuild/wrap/wrap.py", line 72, in open_wrapdburl
    return urllib.request.urlopen(urlstring, timeout=req_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 548, in _open
    'unknown_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1387, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
```

**Comment by dota17** [comment]
We don't use `meson wrap install jsoncpp` command to install jsoncpp. Do you really follow exactly the step from the building part of the Wiki? Is the log you post complete? Is your network connected correctly?

**Comment by dota17** [comment]
Well, I guess you refered the README: [The Meson Build System](https://github.com/open-source-parsers/jsoncpp/blob/master/README.md#the-meson-build-system), I followed it too just now, and failed too. Actually, I always compile this lib with meson follow the steps in [CONTRIBUTING.md](https://github.com/open-source-parsers/jsoncpp/blob/master/CONTRIBUTING.md#building-and-testing-with-mesonninja) or [Wiki](https://github.com/open-source-parsers/jsoncpp/wiki/Building#building-and-testing-with-mesonninja)(they are the same).

What's more, the jsoncpp in Meson WrapDB is 1.8.4. If you run `meson wrap install jsoncpp` success,
it's not the latest one. So, I recommend not using this command.

**Comment by cdunn2001** [comment]
Yes, we need a version bump. But also, we aren't responsible for the code in WrapDB. And to the extent that WrapDB works at all, the versions need to be consistent.

**Comment by gg256** [comment]
to build the  latest version is easier, just do :
cmake .
make
