### ISSUE TITLE
rasberry pi 3 make error

### ISSUE THREAD

**Issue by zewenhs** [open-source-parsers/jsoncpp#732]
Hi all:
after install ninja and meson successfully on raspi 3, there have errors when compiling, the log as:
How this going on?? thanks!!!!

```
pi@raspberrypi:~/jsoncpp $ BUILD_TYPE=debug
pi@raspberrypi:~/jsoncpp $ LIB_TYPE=shared
pi@raspberrypi:~/jsoncpp $ meson --buildtype ${BUILD_TYPE} --default-library ${LIB_TYPE} . build-${LIB_TYPE}
The Meson build system
Version: 0.44.0
Source dir: /home/pi/jsoncpp
Build dir: /home/pi/jsoncpp/build-shared
Build type: native build
Project name: jsoncpp
Native C++ compiler: c++ (gcc 4.9.2)
Build machine cpu family: arm
Build machine cpu: armv7l
Configuring version.h using configuration
Build targets in project: 3
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/mesonbuild/mesonmain.py", line 365, in run
    app.generate()
  File "/usr/local/lib/python3.4/dist-packages/mesonbuild/mesonmain.py", line 151, in generate
    self._generate(env)
  File "/usr/local/lib/python3.4/dist-packages/mesonbuild/mesonmain.py", line 208, in _generate
    g.generate(intr)
  File "/usr/local/lib/python3.4/dist-packages/mesonbuild/backend/ninjabackend.py", line 194, in generate
    self.ninja_command = environment.detect_ninja(log=True)
  File "/usr/local/lib/python3.4/dist-packages/mesonbuild/environment.py", line 96, in detect_ninja
    p, found = Popen_safe([n, '--version'])[0:2]
  File "/usr/local/lib/python3.4/dist-packages/mesonbuild/mesonlib.py", line 637, in Popen_safe
    return Popen_safe_legacy(args, write=write, stderr=stderr, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mesonbuild/mesonlib.py", line 648, in Popen_safe_legacy
    stderr=stderr, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
```

**Comment by cdunn2001** [comment]
I'm glad you're using Meson!

But to fix this problem, we will need help. Can you submit a PR?

**Comment by BillyDonahue** [comment]
If I'm following correctly, I think you have meson trying to invoke ninja.
The pipe executing Ninja is then throwing because ninja isn't the right kind of ARM executable, and meson isn't built to catch that exception.

https://askubuntu.com/questions/648555/bash-program-cannot-execute-binary-file-exec-format-error

I see that meson is in /usr/local, so maybe you've manually downloaded your own meson and/or ninja, and they're built for the wrong ARM subarchitecture?

I'd be curious to know what happens when you run ninja standalone?

In any case, it doesn't look like a jsoncpp problem.
