### ISSUE TITLE
debug help wanted corrupted size vs. prev_size in jsoncpp

### ISSUE THREAD

**Issue by xjtuwjp** [open-source-parsers/jsoncpp#825]
We're using libjsoncpp for parsing json output from QEMU, after update from Debian Jessie(libjsoncpp 0.6.0~rc2-3.1 )  to Stretch (libjsoncpp 1.7.4-3), we hit Sigabort, full call trace is below:

'''
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 140692451321689, 0, 140692450891799, 140692454200832, 3432, 140692454181120, 140692454184000, 94362861470688, 140692450888546, 7795484802351636512, 872, 0, 3432, 0, 140692475821120}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007ff5838af42a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x5d6f7364765b2020, sa_sigaction = 0x5d6f7364765b2020}, sa_mask = {__val = {7378697629483820554, 3472328296331896422, 7378697629483806000, 3472609797883717222, 2337500343188860976, 3472328296227680304, 3467824696768081952, 2314885530818453536, 2314885530818453536, 7166204968890474528, 3472385308382489697, 3467895053655089200, 2319406791738273840, 3689890873941307440, 2314885530820031794, 140736086339232}}, sa_flags = 82, sa_restorer = 0x7fffac6eeea0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ff5838ebc00 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ff5839e0d98 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
        ap = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fffac6eeeb0, reg_save_area = 0x7fffac6eee40}}
        fd = 2
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x00007ff5838f1fc6 in malloc_printerr (action=3, str=0x7ff5839dd8de "corrupted size vs. prev_size", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5049
        buf = "000055d290c6c4f0" 
        cp = <optimized out>
        ar_ptr = <optimized out>
        ptr = <optimized out>
        str = 0x7ff5839dd8de "corrupted size vs. prev_size" 
        action = 3
#4  0x00007ff5838f462f in _int_malloc (av=av@entry=0x7ff583c14b00 <main_arena>, bytes=bytes@entry=88) at malloc.c:3765
        p = 0x55d290c6c4f0
        iters = <optimized out>
        nb = 96
        idx = 7
        bin = <optimized out>
        victim = 0x55d290c6c4f0
        size = <optimized out>
        victim_index = <optimized out>
        remainder = <optimized out>
        remainder_size = 416
        block = <optimized out>
        bit = <optimized out>
        map = <optimized out>
        fwd = <optimized out>
        bck = <optimized out>
        errstr = 0x0
        __func__ = "_int_malloc" 
#5  0x00007ff5838f5f64 in __GI___libc_malloc (bytes=bytes@entry=88) at malloc.c:2928
        ar_ptr = 0x7ff583c14b00 <main_arena>
        victim = <optimized out>
        hook = <optimized out>
        __func__ = "__libc_malloc" 
#6  0x00007ff5840dd7a8 in operator new (sz=sz@entry=88) at ../../../../src/libstdc++-v3/libsupc++/new_op.cc:50
        p = <optimized out>
#7  0x00007ff5845fc3d6 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value> > >::allocate (this=<optimized out>, __n=1) at /usr/include/c++/6/ext/new_allocator.h:104
No locals.
#8  std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value> > > >::allocate (__a=..., __n=1) at /usr/include/c++/6/bits/alloc_traits.h:416
No locals.
#9  std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_M_get_node (this=<optimized out>) at /usr/include/c++/6/bits/stl_tree.h:505
No locals.
#10 std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_M_create_node<std::pair<Json::Value::CZString const, Json::Value>&> (this=<optimized out>) at /usr/include/c++/6/bits/stl_tree.h:559
        __tmp = <optimized out>
#11 std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_Alloc_node::operator()<std::pair<Json::Value::CZString const, Json::Value>&> (this=<optimized out>, __arg=...) at /usr/include/c++/6/bits/stl_tree.h:473
No locals.
#12 std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_M_insert_<std::pair<Json::Value::CZString const, Json::Value>&, std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_Alloc_node> (__node_gen=..., __v=..., __p=0x55d290c6b870, __x=<optimized out>, this=0x55d290c6b9f0) at /usr/include/c++/6/bits/stl_tree.h:1510
        __insert_left = false
        __z = <optimized out>
#13 std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_M_insert_unique_<std::pair<Json::Value::CZString const, Json::Value>&, std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_Alloc_node> (this=0x55d290c6b9f0, __position=..., __position@entry=..., __v=..., __node_gen=...) at /usr/include/c++/6/bits/stl_tree.h:1979
        __res = <optimized out>
#14 0x00007ff5845fc57e in std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_M_insert_unique_<std::pair<Json::Value::CZString const, Json::Value>&> (__x=..., __pos=..., this=<optimized out>) at /usr/include/c++/6/bits/stl_tree.h:950
No locals.
#15 std::map<Json::Value::CZString, Json::Value, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::insert<std::pair<Json::Value::CZString const, Json::Value>&, void> (__x=..., __position=..., this=<optimized out>) at /usr/include/c++/6/bits/stl_map.h:794
No locals.
#16 Json::Value::operator[] (this=0x55d290c6bad0, index=index@entry=1) at ./src/lib_json/json_value.cpp:988
        key = {cstr_ = 0x0, {index_ = 1, storage_ = {policy_ = 1, length_ = 0}}}
        it = <optimized out>
        defaultValue = {first = {cstr_ = 0x0, {index_ = 1, storage_ = {policy_ = 1, length_ = 0}}}, second = {static null = @0x55d290c4bcf0, static nullRef = @0x55d290c4bcf0, static minLargestInt = -9223372036854775808, static maxLargestInt = 9223372036854775807, static maxLargestUInt = 18446744073709551615, static minInt = -2147483648, static maxInt = 2147483647, static maxUInt = 4294967295, static minInt64 = -9223372036854775808, static maxInt64 = 9223372036854775807, static maxUInt64 = 18446744073709551615, value_ = {int_ = 0, uint_ = 0, real_ = 0, bool_ = false, string_ = 0x0, map_ = 0x0}, type_ = Json::nullValue, allocated_ = 0, comments_ = 0x0, start_ = 0, limit_ = 0}}
#17 0x00007ff5845fc927 in Json::Value::operator[] (this=<optimized out>, index=index@entry=1) at ./src/lib_json/json_value.cpp:996
No locals.
#18 0x00007ff5845f03d0 in Json::Reader::readArray (this=this@entry=0x7fffac6ef9e0, tokenStart=...) at ./src/lib_json/json_reader.cpp:531
        value = <optimized out>
        ok = <optimized out>
        token = {type_ = Json::Reader::tokenArraySeparator, start_ = 0x55d290c6b050 ", {\"arch\": \"x86\", \"current\": false, \"CPU\": 1, \"qom_path\": \"/machine/unattached/device[2]\", \"pc\": -2123711472, \"halted\": false, \"thread_id\": 17412}, {\"arch\": \"x86\", \"current\": false, \"CPU\": 2, \"qom_pat"..., end_ = 0x55d290c6b051 " {\"arch\": \"x86\", \"current\": false, \"CPU\": 1, \"qom_path\": \"/machine/unattached/device[2]\", \"pc\": -2123711472, \"halted\": false, \"thread_id\": 17412}, {\"arch\": \"x86\", \"current\": false, \"CPU\": 2, \"qom_path"...}
        badTokenType = <optimized out>
        init = {static null = @0x55d290c4bcf0, static nullRef = @0x55d290c4bcf0, static minLargestInt = -9223372036854775808, static maxLargestInt = 9223372036854775807, static maxLargestUInt = 18446744073709551615, static minInt = -2147483648, static maxInt = 2147483647, static maxUInt = 4294967295, static minInt64 = -9223372036854775808, static maxInt64 = 9223372036854775807, static maxUInt64 = 18446744073709551615, value_ = {int_ = 0, uint_ = 0, real_ = 0, bool_ = false, string_ = 0x0, map_ = 0x0}, type_ = Json::nullValue, allocated_ = 0, comments_ = 0x0, start_ = 0, limit_ = 0}
        index = 2
#19 0x00007ff5845f023b in Json::Reader::readValue (this=this@entry=0x7fffac6ef9e0) at ./src/lib_json/json_reader.cpp:186
        token = {type_ = Json::Reader::tokenArrayBegin, start_ = 0x55d290c6afbc "[{\"arch\": \"x86\", \"current\": true, \"CPU\": 0, \"qom_path\": \"/machine/unattached/device[0]\", \"pc\": 140043817632820, \"halted\": false, \"thread_id\": 17411}, {\"arch\": \"x86\", \"current\": false, \"CPU\": 1, \"qom_p"..., end_ = 0x55d290c6afbd "{\"arch\": \"x86\", \"current\": true, \"CPU\": 0, \"qom_path\": \"/machine/unattached/device[0]\", \"pc\": 140043817632820, \"halted\": false, \"thread_id\": 17411}, {\"arch\": \"x86\", \"current\": false, \"CPU\": 1, \"qom_pa"...}
        successful = true
#20 0x00007ff5845efb73 in Json::Reader::readObject (this=this@entry=0x7fffac6ef9e0, tokenStart=...) at ./src/lib_json/json_reader.cpp:496
        colon = {type_ = Json::Reader::tokenMemberSeparator, start_ = 0x55d290c6afba ": [{\"arch\": \"x86\", \"current\": true, \"CPU\": 0, \"qom_path\": \"/machine/unattached/device[0]\", \"pc\": 140043817632820, \"halted\": false, \"thread_id\": 17411}, {\"arch\": \"x86\", \"current\": false, \"CPU\": 1, \"qom"..., end_ = 0x55d290c6afbb " [{\"arch\": \"x86\", \"current\": true, \"CPU\": 0, \"qom_path\": \"/machine/unattached/device[0]\", \"pc\": 140043817632820, \"halted\": false, \"thread_id\": 17411}, {\"arch\": \"x86\", \"current\": false, \"CPU\": 1, \"qom_"...}
        value = <optimized out>
        ok = <optimized out>
        comma = {type_ = 2428943056, start_ = 0x0, end_ = 0x7fffac6ef720 "\373\006"}
        finalizeTokenOk = <optimized out>
        initialTokenOk = true
        tokenName = {type_ = Json::Reader::tokenString, start_ = 0x55d290c6afb2 "\"return\": [{\"arch\": \"x86\", \"current\": true, \"CPU\": 0, \"qom_path\": \"/machine/unattached/device[0]\", \"pc\": 140043817632820, \"halted\": false, \"thread_id\": 17411}, {\"arch\": \"x86\", \"current\": false, \"CPU\":"..., end_ = 0x55d290c6afba ": [{\"arch\": \"x86\", \"current\": true, \"CPU\": 0, \"qom_path\": \"/machine/unattached/device[0]\", \"pc\": 140043817632820, \"halted\": false, \"thread_id\": 17411}, {\"arch\": \"x86\", \"current\": false, \"CPU\": 1, \"qom"...}
        name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffac6ef610 "return"}, _M_string_length = 6, {_M_local_buf = "return\000\000\200\273\026\204\365\177\000", _M_allocated_capacity = 121437875889522}}
        init = {static null = @0x55d290c4bcf0, static nullRef = @0x55d290c4bcf0, static minLargestInt = -9223372036854775808, static maxLargestInt = 9223372036854775807, static maxLargestUInt = 18446744073709551615, static minInt = -2147483648, static maxInt = 2147483647, static maxUInt = 4294967295, static minInt64 = -9223372036854775808, static maxInt64 = 9223372036854775807, static maxUInt64 = 18446744073709551615, value_ = {int_ = 1787, uint_ = 1787, real_ = 8.8289530911830757e-321, bool_ = 251, string_ = 0x6fb <error: Cannot access memory at address 0x6fb>, map_ = 0x6fb}, type_ = Json::nullValue, allocated_ = 0, comments_ = 0x0, start_ = 0, limit_ = 0}
#21 0x00007ff5845f0033 in Json::Reader::readValue (this=this@entry=0x7fffac6ef9e0) at ./src/lib_json/json_reader.cpp:182
        token = {type_ = Json::Reader::tokenObjectBegin, start_ = 0x55d290c6afb0 "{ \"return\": [{\"arch\": \"x86\", \"current\": true, \"CPU\": 0, \"qom_path\": \"/machine/unattached/device[0]\", \"pc\": 140043817632820, \"halted\": false, \"thread_id\": 17411}, {\"arch\": \"x86\", \"current\": false, \"CPU"..., end_ = 0x55d290c6afb1 " \"return\": [{\"arch\": \"x86\", \"current\": true, \"CPU\": 0, \"qom_path\": \"/machine/unattached/device[0]\", \"pc\": 140043817632820, \"halted\": false, \"thread_id\": 17411}, {\"arch\": \"x86\", \"current\": false, \"CPU\""...}
        successful = true
#22 0x00007ff5845f0756 in Json::Reader::parse (this=this@entry=0x7fffac6ef9e0, beginDoc=0x55d290c6afb0 "{ \"return\": [{\"arch\": \"x86\", \"current\": true, \"CPU\": 0, \"qom_path\": \"/machine/unattached/device[0]\", \"pc\": 140043817632820, \"halted\": false, \"thread_id\": 17411}, {\"arch\": \"x86\", \"current\": false, \"CPU"..., endDoc=0x55d290c6b6b9 "", root=..., collectComments=<optimized out>, collectComments@entry=true) at ./src/lib_json/json_reader.cpp:142
        successful = <optimized out>
        token = {type_ = 2892953920, start_ = 0x55d290c6f9d0 "\230O\301\203\365\177", end_ = 0x55d290c6fbd0 " \"/machia\003"}
#23 0x00007ff5845f08f0 in Json::Reader::parse (this=0x7fffac6ef9e0, document=..., root=..., collectComments=collectComments@entry=true) at ./src/lib_json/json_reader.cpp:105
        documentCopy = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffac6ef890 ""}, _M_string_length = 0, {_M_local_buf = "\000\000\000\000\000\000\000\000w\000\000\000|\000\000", _M_allocated_capacity = 0}}
        end = <optimized out>

'''

**Comment by xjtuwjp** [comment]
Turns out, it's a bug in our code, so close it
