### ISSUE TITLE
Cannot build with python nor MESON

### ISSUE THREAD

**Issue by rafak360** [open-source-parsers/jsoncpp#988]
**Windows 7 64-bit
Tested on Python 2.6 32-bit and 64-bit same error output**

```
C:\jsoncpp-master>python amalgamate.py
Amalgamating header...
Traceback (most recent call last):
  File "amalgamate.py", line 155, in <module>
    main()
  File "amalgamate.py", line 147, in main
    header_include_path=options.header_include_path)
  File "amalgamate.py", line 69, in amalgamate_source
    header.add_file("include/json/version.h")
  File "amalgamate.py", line 30, in add_file
    f = open(os.path.join(self.top_dir, relative_input_path), "rt")
IOError: [Errno 2] No such file or directory: 'C:\\jsoncpp-master\\include/json/
version.h'
```
I just followed these steps: [Amalgamated source](https://github.com/open-source-parsers/jsoncpp/wiki/Amalgamated) but it's not working for me, why?

**EDIT:**
I tried with MESON, but it didn't help:

```
Build started at 2019-07-17T18:38:44.657486
Main binary: c:\users\userexample\appdata\local\programs\python\python37\python.exe
Python system: Windows
The Meson build system
Version: 0.51.1
Source dir: C:\jsoncpp-master
Build dir: C:\jsoncpp-master\builddir
Build type: native build
Project name: jsoncpp
Project version: 1.9.0

meson.build:1:0: ERROR: Unknown compiler(s): ['icl', 'cl', 'c++', 'g++', 'clang++', 'clang-cl']
The follow exceptions were encountered:
Running "icl " gave "[WinError 2] The system cannot find the file specified"
Running "cl /?" gave "[WinError 2] The system cannot find the file specified"
Running "c++ --version" gave "[WinError 2] The system cannot find the file specified"
Running "g++ --version" gave "[WinError 2] The system cannot find the file specified"
Running "clang++ --version" gave "[WinError 2] The system cannot find the file specified"
Running "clang-cl /?" gave "[WinError 2] The system cannot find the file specified"
```

**Comment by baylesj** [comment]
Looks like your meson isn't working because you don't have a compiler installed.

I have a fix for the amalgamate script, this has been an evolving issue recently. I will close this issue when that PR is checked in, thanks!

**Comment by rafak360** [comment]
> Looks like your meson isn't working because you don't have a compiler installed.
> 
> I have a fix for the amalgamate script, this has been an evolving issue recently. I will close this issue when that PR is checked in, thanks!

Thank you, your fix worked for me, I could build that by the amalgamate script, it should be merged in the master branch which is really a mess.
